System:
  Database:
    # Databases Supported:
    # mysql, sqlite

    Type: 'sqlite'
    # [MySQL Default] mysql://localhost:3306/database_name
    URL: 'mysql://localhost:3306/CompleteEconomy'

    # Login details for MySQL database
    Username: ''
    Password: ''

  Currency:
    Prefix: '[MONEY]'
    MajorSingle: Dollar
    MajorPlural: Dollars
    # Major: [ 'Dollar', 'Dollars' ] // Would prefer this method
    MinorSingle: Cent
    MinorPlural: Cents
    # Minor: [ 'Cent', 'Cents' ] // Would prefer this method

    # Controls how money is formatted through methods
    # Example (separate) 1 Dollar 23 Cents
    # Example (combined) 0.23 Dollars and 1.23 Dollars
    Formatting: combined
    
    # Purges all cash on hand when player dies
    PurgeOnDeath: true

  Default:
    # Default account balance when created
    Holdings: 30.0

  Purging:
    Enabled: true

    #Days to purge inactive accounts
    Interval: 14
