System:
  Database:
    # Databases Supported:
    # mysql, sqlite

    Type: 'sqlite'
    # [MySQL Default] mysql://localhost:3306/database_name
    URL: 'mysql://localhost:3306/CompleteEconomy'

    # Login details for MySQL database
    Username: ''
    Password: ''

  Currency:
    # Major is the first segment [Major].Minor
    MajorSingle: Dollar
    MajorPlural: Dollars
    # Major: [ 'Dollar', 'Dollars' ]


    # Minor is the second segment Major.[Minor]
    MinorSingle: Cent
    MinorPlural: Cents
    # Minor: [ 'Cent', 'Cents' ]

  # Controls how money is formatted through methods
  Formatting:
    # Separate allows you to use the Minor amounts for amounts < 1
    # Example (true) 0.23 Cents and 1.23 Dollars (false) 0.23 Dollars and 1.23 Dollars
    Separate: false

  Default:
    # Default account balance when created
    Holdings: 30.0

  # Logs all monetary transactions passed through CompleteEconomy
  Logging: false

  # Purges Default Balances at Loading
  # Good way to keep unused accounts or default accounts wiped out and lower database usage.
  Purging: true

  # Controls amount of money gained at a set interval.
  Interest:
    Enabled: true

    # Only give interest to players who are currently online?
    Online: true

    # Send a message when the player gains interest?
    Announce: false

    #  Interval is done in seconds, here is a easy reference table for commonly set intervals:
    #  1 minute = 60 seconds
    #  1 hour = 1 minute * 60 = 3600 seconds
    #  1 day = 1 hour * 24 = 86400 seconds
    #  1 Minecraft day = 1200 seconds
    Interval: 1200

    Amount:
      # The balance to be met where we stop giving interest.
      # 0.0 for no limit
      Cutoff: 0.0

      # Percentage of holdings to give / take (Negative to take)
      Percent: 0.1
