System:
  Database:
    # Databases Supported:
    # mysql, sqlite

    Type: 'sqlite'
    # [MySQL Default] mysql://localhost:3306/iConomy
    URL: 'mysql://localhost:3306/CompleteEconomy'

    # Login details for MySQL database
    Username: ''
    Password: ''
