Jobs:
  Enabled: true
  Prefix: '[JOB]'

  MaxJobs:
    Default: 4
    Admins: 6
    
  Earnings:
    # Send a message to player regarding their earnings?
    Announce: true
    # AnnounceInterval is in minutes
    AnnounceInterval: 20

    # PayInterval is in minutes
    PayInterval: 20
    PayCreative: false
    PaySpawners: false
    SpawnerDistance: 8


