author: ccattell
description: Everything your server needs for a fully functioning economy
main: me.ccattell.plugins.completeeconomy.CompleteEconomy
name: Complete Economy
startup: postworld
version: 0.1-a
permissions:
  ceadmin.commanmd:
    description: Allow players to use the CE admin features.
    default: op
  ce.cash:
    description: Allow players to use the /cash command.
    default: false
  ce.pay:
    description: Allow players to use the /pay command.
    default: false
  ce.bank:
    description: Allow players to use the /bank command.
    default: false
  ce.xpbank:
    description: Allow players to use the /xpbank command.
    default: false
commands:
  ceadmin:
    description: The CompleteEconomy command
    usage: /<command>
    permission: ceadmin.command
    permission-message: You don't have permission to use admin commands
  cash:
    description: This will display your bank account balance.
    usage: /<command>
    permission: ce.cash
    permission-message: You don't have permission to use this command
  pay:
    description: This will give [amount] to another player.
    usage: /<command> [amount] [player name]
    permission: ce.pay
    permission-message: You don't have permission to pay other players
  bank:
    aliases: [b]
    description: This will display your bank account balance.
    usage: /<command>
    permission: ce.bank
    permission-message: You don't have permission to use the bank
  xpbank:
    aliases: [xpb]
    description: This will display your XP account balance.
    usage: /<command>
    permission: ce.xpbank
    permission-message: You don't have permission to use the xp bank