author: ccattell
description: Everything your server needs for a fully functioning economy
main: me.ccattell.plugins.completeeconomy.CompleteEconomy
name: Complete Economy
startup: postworld
version: 0.0.1a
permissions:
  ce.admin:
    description: Allow players to use the CE admin features.
    default: op
  ce.command:
    description: Allow players to use the /ce command.
    default: true
commands:
  ce:
    description: The CompleteEconomy command
    usage: /<command>
    permission: ce.command
    permission-message: You don't have the permission <permission> to use this command
  cash:
    description: This will display your bank account balance.
    usage: /<command>
  pay:
    description: This will give [amount] to another player.
    usage: /<command> [amount] [player name]

  bank:
    aliases: [b]
    description: This will display your bank account balance.
    usage: /<command>
    deposit:
      aliases: [d]
      description: This will deposit [amount] to your Bank Account
      usage: /<command> deposit [amount]
    withdrawal:
      aliases: [w]
      description: This will withdrawal [amount] from your Bank Account
      usage: /<command> withdrawal [amount]
  xpbank:
    aliases: [b]
    description: This will display your XP account balance.
    usage: /<command>
    deposit:
      aliases: [d]
      description: This will deposit [amount] to your XP Account
      usage: /<command> deposit [amount]
    withdrawal:
      aliases: [w]
      description: This will withdrawal [amount] from your XP Account
      usage: /<command> withdrawal [amount]
