Shops:
  Enabled: true
  Prefix: '[SHOP]'

  # Only open when player is online?
  Online: false

  # Send a message to owner when someone purchases?
  Announce: true

Kits:
  Enabled: true
  Prefix: '[KIT]'

  # Need to work out how this can be accomplished
  # Allows kits to be made by players to be sold in shops?
  PlayerKits: true
