Titles:
  Prefix: '[TITLES]'
  PromoteAnnounce: true
  Levels:
    Beginner: 
      Level: 0
      Multiplier: 1
    Novice:
      Level: 30
      Multiplier: 1.25
    Apprentice:
      Level: 60
      Multiplier: 1.5
    Journeyman:
      Level: 90
      Multiplier: 2
    Expert:
      Level: 120
      Multiplier: 2.5
    Master:
      Level: 150
      Multiplier: 3
    GrandMaster:
      Level: 180
      Multiplier: 4